/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgumentariumRouteImport } from './routes/agumentarium'
import { Route as CodexRouteImport } from './routes/codex'
import { Route as ConditionariumRouteImport } from './routes/conditionarium'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as ProtocolosRouteImport } from './routes/protocolos'
import { Route as TomarRouteImport } from './routes/tomar'
import { Route as DiaDayRouteImport } from './routes/dia.$day'
import { Route as AbrirKindIdRouteImport } from './routes/abrir.$kind.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgumentariumRoute = AgumentariumRouteImport.update({
  id: '/agumentarium',
  path: '/agumentarium',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexRoute = CodexRouteImport.update({
  id: '/codex',
  path: '/codex',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionariumRoute = ConditionariumRouteImport.update({
  id: '/conditionarium',
  path: '/conditionarium',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolosRoute = ProtocolosRouteImport.update({
  id: '/protocolos',
  path: '/protocolos',
  getParentRoute: () => rootRouteImport,
} as any)
const TomarRoute = TomarRouteImport.update({
  id: '/tomar',
  path: '/tomar',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaDayRoute = DiaDayRouteImport.update({
  id: '/dia/$day',
  path: '/dia/$day',
  getParentRoute: () => rootRouteImport,
} as any)
const AbrirKindIdRoute = AbrirKindIdRouteImport.update({
  id: '/abrir/$kind/$id',
  path: '/abrir/$kind/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agumentarium': typeof AgumentariumRoute
  '/codex': typeof CodexRoute
  '/conditionarium': typeof ConditionariumRoute
  '/journal': typeof JournalRoute
  '/protocolos': typeof ProtocolosRoute
  '/tomar': typeof TomarRoute
  '/dia/$day': typeof DiaDayRoute
  '/abrir/$kind/$id': typeof AbrirKindIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agumentarium': typeof AgumentariumRoute
  '/codex': typeof CodexRoute
  '/conditionarium': typeof ConditionariumRoute
  '/journal': typeof JournalRoute
  '/protocolos': typeof ProtocolosRoute
  '/tomar': typeof TomarRoute
  '/dia/$day': typeof DiaDayRoute
  '/abrir/$kind/$id': typeof AbrirKindIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agumentarium': typeof AgumentariumRoute
  '/codex': typeof CodexRoute
  '/conditionarium': typeof ConditionariumRoute
  '/journal': typeof JournalRoute
  '/protocolos': typeof ProtocolosRoute
  '/tomar': typeof TomarRoute
  '/dia/$day': typeof DiaDayRoute
  '/abrir/$kind/$id': typeof AbrirKindIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agumentarium'
    | '/codex'
    | '/conditionarium'
    | '/journal'
    | '/protocolos'
    | '/tomar'
    | '/dia/$day'
    | '/abrir/$kind/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agumentarium'
    | '/codex'
    | '/conditionarium'
    | '/journal'
    | '/protocolos'
    | '/tomar'
    | '/dia/$day'
    | '/abrir/$kind/$id'
  id:
    | '__root__'
    | '/'
    | '/agumentarium'
    | '/codex'
    | '/conditionarium'
    | '/journal'
    | '/protocolos'
    | '/tomar'
    | '/dia/$day'
    | '/abrir/$kind/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgumentariumRoute: typeof AgumentariumRoute
  CodexRoute: typeof CodexRoute
  ConditionariumRoute: typeof ConditionariumRoute
  JournalRoute: typeof JournalRoute
  ProtocolosRoute: typeof ProtocolosRoute
  TomarRoute: typeof TomarRoute
  DiaDayRoute: typeof DiaDayRoute
  AbrirKindIdRoute: typeof AbrirKindIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agumentarium': {
      id: '/agumentarium'
      path: '/agumentarium'
      fullPath: '/agumentarium'
      preLoaderRoute: typeof AgumentariumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex': {
      id: '/codex'
      path: '/codex'
      fullPath: '/codex'
      preLoaderRoute: typeof CodexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditionarium': {
      id: '/conditionarium'
      path: '/conditionarium'
      fullPath: '/conditionarium'
      preLoaderRoute: typeof ConditionariumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocolos': {
      id: '/protocolos'
      path: '/protocolos'
      fullPath: '/protocolos'
      preLoaderRoute: typeof ProtocolosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tomar': {
      id: '/tomar'
      path: '/tomar'
      fullPath: '/tomar'
      preLoaderRoute: typeof TomarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dia/$day': {
      id: '/dia/$day'
      path: '/dia/$day'
      fullPath: '/dia/$day'
      preLoaderRoute: typeof DiaDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abrir/$kind/$id': {
      id: '/abrir/$kind/$id'
      path: '/abrir/$kind/$id'
      fullPath: '/abrir/$kind/$id'
      preLoaderRoute: typeof AbrirKindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgumentariumRoute: AgumentariumRoute,
  CodexRoute: CodexRoute,
  ConditionariumRoute: ConditionariumRoute,
  JournalRoute: JournalRoute,
  ProtocolosRoute: ProtocolosRoute,
  TomarRoute: TomarRoute,
  DiaDayRoute: DiaDayRoute,
  AbrirKindIdRoute: AbrirKindIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
